chore: add helm
MapColonies/docker-mapproxy pull request #11
Opened 2021-12-23 14:27 UTC by shimoncohen

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2021-12-23 14:50 UTC, asafMasa approved these changes

2021-12-23 14:50 UTC, asafMasa commented on helm/templates/mapproxy-routes.yaml
> +    name: {{ template "map-proxy.fullname" . }}-nginx
nginx?

2022-01-02 12:40 UTC, Yossizz commented on helm/values.yaml
> +pullSecretName: acr-registry
please remove

2022-01-02 12:40 UTC, Yossizz commented on helm/values.yaml
> +  dnshost: apps.v0h0bdx6.eastus.aroapp.io
please remove

2022-01-02 12:41 UTC, Yossizz commented on helm/values.yaml
> +  mapProxyImage: "acrarolibotnonprod.azurecr.io/mapproxy"
please remove

2022-01-02 12:41 UTC, Yossizz requested changes
please remove values

2022-01-03 07:58 UTC, CL-SHLOMIKONCHA requested changes
first, in my opinion its wrong to separate the mapproxy helm from init-container and mapproxinator (how did you checked it with no init-container?)
second,  its not updated to the last helm template that we are using with the common global config.

2022-01-03 07:58 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +environment: development
adapt to the newest helm template and add it to the helper.tpl file, so we can use as global config.

2022-01-03 07:58 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +cloudProvider: azure
adapt to the newest helm template and add it to the helper.tpl file, so we can use as global config.

2022-01-03 07:58 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  S3:
s3 configs should be taken from global config as well

2022-10-26 05:29 UTC, closed without merging