feat: Add tracing for wsgi, sqlite3 and botocore
MapColonies/docker-mapproxy pull request #3
Opened 2021-07-28 16:02 UTC by shimoncohen

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2021-07-28 16:39 UTC, asafMasa requested changes

2021-07-28 16:39 UTC, asafMasa commented on start.sh
> +  # sed -i 's/\(, reloader=True\)*'\)'/, reloader=True\)/g' app.py
why was it commented?
if it's already implemented in app.py and you want to keep the remark add an explanation about why it is commented

2021-07-28 16:43 UTC, asafMasa approved these changes

2021-07-29 09:10 UTC, shimoncohen commented on start.sh
> +  # sed -i 's/\(, reloader=True\)*'\)'/, reloader=True\)/g' app.py
added

2021-07-29 15:22 UTC, asafMasa approved these changes

2021-08-03 20:09 UTC, merged