feat: seperate mapproxy deployments
MapColonies/docker-mapproxy pull request #31
Opened 2023-04-02 12:06 UTC by shimoncohen

2023-04-02 14:20 UTC, CL-SHLOMIKONCHA requested changes

2023-04-02 14:20 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  wms:
wms configs should be added to mapproxy umbrella under 'raster-helm' - 'serving' - 'mapproxyDeployment' values, so we can control those configs easily

2023-04-02 14:20 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  wmts:
wmts configs should be added to mapproxy umbrella under 'raster-helm' - 'serving' - 'mapproxyDeployment' values, so we can control those configs easily

2023-04-02 14:20 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> -  resources:
handle this change (remove it )  in our umbrella in 'raster-helm' - 'serving' - 'mapproxyDeployment'

2023-04-02 14:21 UTC, CL-SHLOMIKONCHA requested changes

2023-04-02 14:21 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx.conf
> +            rewrite ^ {{ .Values.mapproxy.route.path }}/service/wms last;
same Ingress issue

2023-04-02 14:59 UTC, asafMasa requested changes

2023-04-02 14:59 UTC, asafMasa commented on helm/config/nginx.conf
> +    location {{ .Values.mapproxy.route.path }} {
add description for each location purpose

2023-04-02 14:59 UTC, asafMasa commented on helm/values.yaml
> +          cpu: 200m
wms resources should be as defined today after the sizing - as this resources will make them restart

2023-04-03 07:49 UTC, shimoncohen commented on helm/config/nginx.conf
> +    location {{ .Values.mapproxy.route.path }}/service/wmts {
Fixed.

2023-04-03 07:50 UTC, shimoncohen commented on helm/config/nginx.conf
> +            rewrite ^ {{ .Values.mapproxy.route.path }}/service/wms last;
Fixed.

2023-04-03 07:50 UTC, shimoncohen commented on helm/config/nginx.conf
> +    location {{ .Values.mapproxy.route.path }} {
Added.

2023-04-03 07:52 UTC, shimoncohen commented on helm/values.yaml
> +          cpu: 200m
These are values, they are made to change for every env.

2023-04-03 08:19 UTC, ronenkapelian commented on helm/config/nginx.mapproxy.wmts.conf
> +}
validate all cache situation:

1. on WMTS should cache tiles only
   a. after 3 times of "miss" the 4 time will be "hit". validate on logs + cache directory
   b. capabilities - bypass status for "cache_status" log for kvp and restfull - validate not store on cache directory
   2. cache not enabled on WMS

2023-04-03 08:22 UTC, ronenkapelian commented on helm/config/nginx.mapproxy.conf
> +gzip on;
validate!
take 1-2 of the directive and check it working with chrome F12 mode (check the header it is gzip, etc)
i want to be sure the directives are enable and passing to the service

2023-04-03 08:29 UTC, ronenkapelian commented on helm/templates/mapproxy-wms-deployment.yaml
> +    collectord.io/index: {{ quote .Values.splunkIndex }}
there is exists lack (bug)
after the collectord.io/index annotation
you should add the annotation of:
"collectord.io/output: splunk"

also add to the wmts deployment the same

2023-04-03 08:39 UTC, ronenkapelian commented on helm/values.yaml
>      tag: 'latest'
on nginx.cache section on values.yaml (can't comment right there). consider rename or add indent to understand the cache only for WMTS deployment (mabye not should think about it)

2023-04-03 10:29 UTC, shimoncohen commented on helm/values.yaml
> +  wmts:
Added.

2023-04-03 10:30 UTC, shimoncohen commented on helm/values.yaml
> -  resources:
Removed.

2023-04-03 11:09 UTC, shimoncohen commented on helm/config/nginx.mapproxy.wmts.conf
> +proxy_cache_min_uses 3; # Sets the number of requests after which the response will be cached
Fixed.

2023-04-03 11:11 UTC, shimoncohen commented on helm/config/nginx.mapproxy.wmts.conf
> +}
Checked.

2023-04-03 11:14 UTC, shimoncohen commented on helm/templates/mapproxy-wms-deployment.yaml
> +    collectord.io/index: {{ quote .Values.splunkIndex }}
Added.

2023-04-03 11:14 UTC, shimoncohen commented on helm/templates/mapproxy-wmts-deployment.yaml
> +    collectord.io/index: {{ quote .Values.splunkIndex }}
Added.

2023-04-03 11:48 UTC, asafMasa approved these changes

2023-04-04 06:29 UTC, ronenkapelian commented on helm/config/nginx.mapproxy.wmts.conf
> +}
1.a was checked and you saw it working by counting the miss rate configured value? (3)

2023-04-04 06:30 UTC, ronenkapelian commented on helm/values.yaml
>      tag: 'latest'
ok

2023-04-13 11:41 UTC, shimoncohen commented on helm/config/nginx.mapproxy.wmts.conf
> +}
Yes 👍🏻

2023-04-13 11:50 UTC, asafMasa approved these changes

2023-04-13 11:53 UTC, CL-SHLOMIKONCHA approved these changes

2023-04-16 11:38 UTC, AnguIar approved these changes

2023-04-16 11:50 UTC, merged