chore: added jwt payload sub to info logs
MapColonies/docker-mapproxy pull request #33
Opened 2023-05-08 12:41 UTC by CL-SHLOMIKONCHA

2023-05-09 13:51 UTC, asafMasa requested changes
🥇 Very good job!

2023-05-09 13:51 UTC, asafMasa commented on helm/config/jwt.js
> +    var parts = data.split('.').slice(0,2)
add validation to protect from invalid data, exception handling is more expansive then simple validation to avoid it

2023-05-09 13:51 UTC, asafMasa commented on helm/config/nginx.mapproxy.conf
> +proxy_set_header Cookie ""; # ensures that a client cannot pass any prior cookies to the webapp and spoil your cache
revert

2023-05-09 13:51 UTC, asafMasa commented on helm/config/jwt.js
> +        return ""
return "";

2023-05-09 13:51 UTC, asafMasa requested changes
🥇 Very good job!

2023-05-14 07:57 UTC, CL-SHLOMIKONCHA commented on helm/config/jwt.js
> +        return ""
fixed

2023-05-14 07:57 UTC, CL-SHLOMIKONCHA commented on helm/config/nginx.mapproxy.conf
> +proxy_set_header Cookie ""; # ensures that a client cannot pass any prior cookies to the webapp and spoil your cache
fixed

2023-05-14 07:57 UTC, CL-SHLOMIKONCHA commented on helm/config/jwt.js
> +    var parts = data.split('.').slice(0,2)
fixed

2023-05-16 08:30 UTC, asafMasa approved these changes

2023-05-16 08:44 UTC, merged