chore: add uwsgi exporter
MapColonies/docker-mapproxy pull request #45
Opened 2023-11-23 15:29 UTC by nitzanmorr

2023-11-23 15:50 UTC, asafMasa requested changes
good job 👍

2023-11-23 15:50 UTC, asafMasa commented on helm/templates/uwsgi-exporter-container.yaml
> +{{- end }}
end of file

2023-11-23 15:50 UTC, asafMasa commented on helm/values.yaml
> +    enabled: true
please change to false

2023-11-26 09:20 UTC, CL-SHLOMIKONCHA requested changes

2023-11-26 09:20 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  enabled: true
consider remove if it is not in use

2023-11-26 09:21 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  enabled: true
can confuse with 'metric.enabled'

2023-11-26 13:51 UTC, CL-SHLOMIKONCHA approved these changes

2023-11-26 13:52 UTC, asafMasa approved these changes

2023-11-26 13:52 UTC, merged