Opala / Envoy support
MapColonies/docker-mapproxy pull request #51
Opened 2023-12-31 09:29 UTC by CL-SHLOMIKONCHA

2024-01-01 11:48 UTC, asafMasa requested changes
Looking good

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +  enabledOpala: false
rename to correct english - opalaEnabled or enableOpala

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +      customHeaderName: "x-api-key"
why do you set the header if we currently use query param?

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +        requiredDomain: rasterWms
put the default in azure

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +          memory: 128Mi
default should be as in prod env

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +          memory: 128Mi
default should be as in prod env

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +    domain: ""
for what it's being used?

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +    wmsDomain: "rasterWms"
duplicated? 
![image](https://github.com/MapColonies/docker-mapproxy/assets/18442671/0c4a4422-8730-4238-bef1-c7dc50f42cb4)

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +    # enabled: true
why is this marked as a comment?

2024-01-01 11:48 UTC, asafMasa commented on helm/values.yaml
> +    enableLogging: false
log level?

2024-01-01 11:48 UTC, asafMasa commented on helm/config/log_format.conf
> +        {{ if and (not .Values.global.enabledOpala) (.Values.nginx.authorization.enabled) }}
we wan't to preserve '"TokenUser" in all scenarios as our dashboards expect this field in logs

2024-01-01 11:48 UTC, asafMasa commented on helm/config/log_format.conf
> +            '"mapcolonies.time_local":"$time_local",'
check if time_local is being used in dashboards - if it does don't change it as it will affect our dashboards

2024-01-01 11:48 UTC, asafMasa commented on helm/config/log_format.conf
> +map $msec $nanosec {
don't we use infra nginx? this method is already defined in infra, no?

2024-01-02 07:27 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    image: envoyproxy/envoy
fixed

2024-01-02 07:56 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    {{- if not .Values.global.enabledOpala }}
fixed

2024-01-02 07:57 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +  enabledOpala: false
fixed

2024-01-02 07:59 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +      customHeaderName: "x-api-key"
removed

2024-01-02 08:03 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    # enabled: true
removed because route/ingress are now managed by the nginx

2024-01-02 08:24 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    enableLogging: false
added

2024-01-02 08:30 UTC, CL-SHLOMIKONCHA commented on helm/config/log_format.conf
> +        {{ if and (not .Values.global.enabledOpala) (.Values.nginx.authorization.enabled) }}
fixed

2024-01-02 08:40 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +          memory: 128Mi
define in argo/helm install values

2024-01-02 08:40 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +          memory: 128Mi
define in argo/helm install values

2024-01-02 09:02 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    domain: ""
unused, removed

2024-01-02 09:03 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +    wmsDomain: "rasterWms"
yes removed, moved to nginx.auth section

2024-01-02 09:25 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +        requiredDomain: rasterWms
it is the value from azure

2024-01-14 09:53 UTC, asafMasa requested changes

2024-01-14 09:53 UTC, asafMasa commented on helm/values.yaml
> +    enabled: false
is this beeing used? duplicated with https://github.com/MapColonies/docker-mapproxy/pull/51/files/4c77383d8cb8d984bc115775c5efa642d2eaea43..a2c203ceabd0c57fa23602c8ed39a11ea6eb243c#diff-81801117ec01136c8a49bfcd42af8e104f4efad1f2daccda9da9d960eaad5279R259?

2024-01-14 09:53 UTC, asafMasa commented on helm/templates/_tplValues.tpl
> +
add remark for end of example and start of service config

2024-01-14 09:53 UTC, asafMasa commented on helm/templates/_resources.tpl
> +{{- end }}
end of file?

2024-01-14 11:04 UTC, CL-SHLOMIKONCHA commented on helm/test.yaml
> +---
fixed

2024-01-14 11:19 UTC, CL-SHLOMIKONCHA commented on helm/values.yaml
> +      enabled: false
yes, defines if WMS authorization is needed or not

2024-01-14 12:11 UTC, CL-SHLOMIKONCHA commented on helm/templates/_tplValues.tpl
> +
fixed

2024-01-14 12:11 UTC, CL-SHLOMIKONCHA commented on helm/templates/_resources.tpl
> +{{- end }}
fixed

2024-01-18 11:29 UTC, asafMasa approved these changes

2024-01-18 12:18 UTC, asafMasa approved these changes

2024-01-18 12:20 UTC, merged